os: linux
dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"

install:
  - pip install tox-travis
script:
  - tox

matrix:
  include:
    - python: "2.7"
      env: TOXENV=flake8
